metadata description = 'Additive deployment of one private Windows 11 AVD personal session host.'

@description('Windows computer name derived from the RITM number. Maximum 15 characters.')
@minLength(4)
@maxLength(15)
param vmName string

@description('Azure region for the VM and NIC.')
param location string = resourceGroup().location

@description('Fixed POC VM size.')
param vmSize string = 'Standard_E4bs_v5'

@description('Full resource ID of the private session-host subnet.')
param subnetId string

@description('Existing AVD personal host-pool name.')
param hostPoolName string

@description('ServiceNow RITM number retained as a resource tag.')
param ritmNumber string

@description('Requested-for UPN retained as a resource tag.')
param requestedForUpn string

@description('Use Gallery for the corporate image or Marketplace for a fresh Microsoft image.')
@allowed([
  'Gallery'
  'Marketplace'
])
param imageSourceType string = 'Gallery'

@description('Full Azure Compute Gallery image-version resource ID. Required when imageSourceType is Gallery.')
param galleryImageVersionId string = ''

@description('Marketplace image fallback used for initial testing before the corporate image is published.')
param marketplaceImage object = {
  publisher: 'MicrosoftWindowsDesktop'
  offer: 'windows-11'
  sku: 'win11-24h2-ent'
  version: 'latest'
}

@description('Current Microsoft AVD DSC configuration package URI. Keep this explicit and version controlled.')
param avdDscConfigurationUri string

@description('AVD registration token generated immediately before this deployment.')
@secure()
param registrationToken string

@description('Local break-glass administrator name. Interactive administration should normally use Entra ID.')
param localAdminUsername string = 'avdlocaladmin'

@description('Ephemeral local administrator password generated by the pipeline.')
@secure()
param localAdminPassword string

@description('Microsoft Intune enterprise application ID used by AADLoginForWindows for MDM enrollment.')
param mdmId string = '0000000a-0000-0000-c000-000000000000'

@description('OS disk SKU.')
@allowed([
  'StandardSSD_LRS'
  'Premium_LRS'
])
param osDiskSku string = 'StandardSSD_LRS'

@description('Enable accelerated networking only when the selected VM SKU supports it.')
param acceleratedNetworking bool = true

@description('Additional tags. Required lifecycle tags cannot be overridden.')
param tags object = {}

var requiredTags = {
  ManagedBy: 'AzureVirtualDesktopPoc'
  Workload: 'AVDSessionHost'
  RITM: ritmNumber
  RequestedFor: requestedForUpn
}
var effectiveTags = union(tags, requiredTags)
var nicName = '${toLower(vmName)}-nic'

resource nic 'Microsoft.Network/networkInterfaces@2024-05-01' = {
  name: nicName
  location: location
  tags: effectiveTags
  properties: {
    enableAcceleratedNetworking: acceleratedNetworking
    ipConfigurations: [
      {
        name: 'ipconfig1'
        properties: {
          privateIPAllocationMethod: 'Dynamic'
          subnet: {
            id: subnetId
          }
        }
      }
    ]
  }
}

resource vm 'Microsoft.Compute/virtualMachines@2024-03-01' = {
  name: vmName
  location: location
  tags: effectiveTags
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    licenseType: 'Windows_Client'
    hardwareProfile: {
      vmSize: vmSize
    }
    storageProfile: {
      imageReference: imageSourceType == 'Gallery'
        ? {
            id: galleryImageVersionId
          }
        : marketplaceImage
      osDisk: {
        name: '${toLower(vmName)}-osdisk'
        createOption: 'FromImage'
        deleteOption: 'Delete'
        caching: 'ReadWrite'
        managedDisk: {
          storageAccountType: osDiskSku
        }
      }
    }
    osProfile: {
      computerName: vmName
      adminUsername: localAdminUsername
      adminPassword: localAdminPassword
      allowExtensionOperations: true
      windowsConfiguration: {
        provisionVMAgent: true
        enableAutomaticUpdates: true
      }
    }
    networkProfile: {
      networkInterfaces: [
        {
          id: nic.id
          properties: {
            deleteOption: 'Delete'
          }
        }
      ]
    }
    securityProfile: {
      securityType: 'TrustedLaunch'
      uefiSettings: {
        secureBootEnabled: true
        vTpmEnabled: true
      }
    }
    diagnosticsProfile: {
      bootDiagnostics: {
        enabled: true
      }
    }
  }
}

resource entraJoinAndIntune 'Microsoft.Compute/virtualMachines/extensions@2024-03-01' = {
  parent: vm
  name: 'AADLoginForWindows'
  location: location
  properties: {
    publisher: 'Microsoft.Azure.ActiveDirectory'
    type: 'AADLoginForWindows'
    typeHandlerVersion: '1.0'
    autoUpgradeMinorVersion: true
    settings: {
      mdmId: mdmId
    }
  }
}

resource avdRegistration 'Microsoft.Compute/virtualMachines/extensions@2024-03-01' = {
  parent: vm
  name: 'MicrosoftPowershellDSC'
  location: location
  properties: {
    publisher: 'Microsoft.Powershell'
    type: 'DSC'
    typeHandlerVersion: '2.83'
    autoUpgradeMinorVersion: true
    settings: {
      modulesUrl: avdDscConfigurationUri
      configurationFunction: 'Configuration.ps1\\AddSessionHost'
      properties: {
        hostPoolName: hostPoolName
        aadJoin: true
      }
    }
    protectedSettings: {
      properties: {
        registrationInfoToken: registrationToken
      }
    }
  }
  dependsOn: [
    entraJoinAndIntune
  ]
}

output vmId string = vm.id
output vmName string = vm.name
output privateNicId string = nic.id
output principalId string = vm.identity.principalId
