# Generated by Build-IntunePackage.ps1 for Machine/CustomCompliance. Edit the source, not this file.
#requires -Version 5.1

<#
.SYNOPSIS
    Runs a full HardeningKitty CIS Windows 11 24H2 audit with Intune-safe output.

.DESCRIPTION
    This audit-only adapter invokes the pinned, unmodified HardeningKitty 0.9.4 engine
    against its CIS Microsoft Windows 11 Enterprise 24H2/v4.0.0 machine or user list.
    It validates every engine file, fails closed on incomplete evaluation, and translates
    the CSV result into deterministic Remediations or Custom Compliance output.
#>

[CmdletBinding()]
param(
    [ValidateSet('Machine', 'User')]
    [string]$Scope = 'Machine',

    [ValidateSet('Detailed', 'IntuneRemediation', 'CustomCompliance')]
    [string]$OutputMode = 'CustomCompliance',

    [string]$EngineRoot = '',

    [string]$ReportPath = '',

    [switch]$PassThru
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$script:AssessmentVersion = '2.0.0'
$script:EngineVersion = '0.9.4'
$script:EngineCommit = 'da0976073caad006c48b2478588c2f7fa572ab46'
$script:PackageManifestSha256 = '6EC3F28E8FC111C5DEC510B62F465BD5B2F0F8290EC8DFA294EC423137D0C848'
$script:BenchmarkName = 'CIS Microsoft Windows 11 Enterprise Benchmark'
$script:BenchmarkVersion = '4.0.0'
$script:TargetRelease = 'Windows 11 24H2'
$script:StartedUtc = [DateTime]::UtcNow
$script:EngineVerified = $false

function ConvertTo-SafeText {
    [CmdletBinding()]
    param(
        [AllowNull()] [object]$Value,
        [int]$MaximumLength = 300
    )

    if ($null -eq $Value) {
        return '<null>'
    }
    $text = if ($Value -is [System.Array]) { ($Value | ForEach-Object { [string]$_ }) -join ',' } else { [string]$Value }
    $text = $text -replace '[\r\n\t]+', ' '
    if ($text.Length -gt $MaximumLength) {
        return $text.Substring(0, $MaximumLength) + '...'
    }
    return $text
}

function Get-DefaultEngineRoot {
    $programFiles64 = if (-not [string]::IsNullOrWhiteSpace($env:ProgramW6432)) { $env:ProgramW6432 } else { $env:ProgramFiles }
    if ([string]::IsNullOrWhiteSpace($programFiles64)) {
        throw 'Unable to determine the 64-bit Program Files directory.'
    }
    return Join-Path $programFiles64 "CISWindowsEndpointAssessment\HardeningKitty\$($script:EngineVersion)"
}

function Get-CategorySettingMap {
    [ordered]@{
        'Account Policies'                              = 'AccountPoliciesCompliant'
        'Administrative Templates: Control Panel'      = 'AdminTemplatesControlPanelCompliant'
        'Administrative Templates: Network'            = 'AdminTemplatesNetworkCompliant'
        'Administrative Templates: Printers'           = 'AdminTemplatesPrintersCompliant'
        'Administrative Templates: Start Menu and Taskbar' = 'AdminTemplatesStartMenuAndTaskbarCompliant'
        'Administrative Templates: System'             = 'AdminTemplatesSystemCompliant'
        'Administrative Templates: Windows Components' = 'AdminTemplatesWindowsComponentsCompliant'
        'Advanced Audit Policy Configuration'          = 'AdvancedAuditPolicyCompliant'
        'Microsoft Defender Application Guard'         = 'DefenderApplicationGuardCompliant'
        'MSS (Legacy)'                                  = 'MSSLegacyCompliant'
        'MS Security Guide'                             = 'MSSecurityGuideCompliant'
        'Security Options'                              = 'SecurityOptionsCompliant'
        'System Services'                               = 'SystemServicesCompliant'
        'User Rights Assignment'                       = 'UserRightsAssignmentCompliant'
        'Windows Firewall'                              = 'WindowsFirewallCompliant'
    }
}

function Get-ScopeCategoryNames {
    $map = Get-CategorySettingMap
    if ($Scope -eq 'User') {
        return @(
            $map['Administrative Templates: Start Menu and Taskbar']
            $map['Administrative Templates: System']
            $map['Administrative Templates: Windows Components']
        )
    }
    return @($map.Values)
}

function Test-TargetPlatform {
    if ($env:OS -ne 'Windows_NT') {
        throw 'This assessment must run on Windows.'
    }
    if (-not [Environment]::Is64BitProcess) {
        throw 'Run the assessment in 64-bit Windows PowerShell.'
    }

    $os = Get-CimInstance -ClassName Win32_OperatingSystem -ErrorAction Stop
    if ([int]$os.ProductType -ne 1 -or [int]$os.BuildNumber -ne 26100) {
        throw "This package targets Windows 11 24H2 client build 26100; detected build $($os.BuildNumber), product type $($os.ProductType)."
    }

    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    if ($Scope -eq 'Machine') {
        $principal = New-Object Security.Principal.WindowsPrincipal($identity)
        if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
            throw 'The machine assessment requires administrative or SYSTEM context.'
        }
    }
    elseif ($identity.User.Value -eq 'S-1-5-18') {
        throw 'The user assessment must run using the logged-on user credentials, not SYSTEM.'
    }

    $locale = (Get-WinSystemLocale -ErrorAction Stop).Name
    if ($locale -ne 'en-US') {
        throw "HardeningKitty 0.9.4 warns that language-dependent analyses can be inaccurate outside en-US; detected $locale."
    }
}

function Test-EnginePackage {
    [CmdletBinding()]
    param([Parameter(Mandatory)] [string]$Root)

    $manifestPath = Join-Path $Root 'PackageManifest.psd1'
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
        throw "Pinned engine package manifest not found at $manifestPath."
    }
    $manifestHash = (Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256 -ErrorAction Stop).Hash
    if ($manifestHash -ne $script:PackageManifestSha256) {
        throw "Engine package manifest hash mismatch. Expected $($script:PackageManifestSha256); found $manifestHash."
    }

    $manifest = Import-PowerShellDataFile -LiteralPath $manifestPath -ErrorAction Stop
    if ($manifest.EngineVersion -ne $script:EngineVersion -or $manifest.SourceCommit -ne $script:EngineCommit) {
        throw 'Engine package version or source commit does not match the adapter pin.'
    }

    foreach ($entry in $manifest.Files.GetEnumerator()) {
        $path = Join-Path $Root ([string]$entry.Key)
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            throw "Required engine file is missing: $($entry.Key)."
        }
        $actualHash = (Get-FileHash -LiteralPath $path -Algorithm SHA256 -ErrorAction Stop).Hash
        if ($actualHash -ne [string]$entry.Value) {
            throw "Engine file hash mismatch: $($entry.Key)."
        }
    }

    $machineList = Join-Path $Root 'lists\finding_list_cis_microsoft_windows_11_enterprise_24h2_machine.csv'
    $userList = Join-Path $Root 'lists\finding_list_cis_microsoft_windows_11_enterprise_24h2_user.csv'
    $machineCount = @(Import-Csv -LiteralPath $machineList -ErrorAction Stop).Count
    $userCount = @(Import-Csv -LiteralPath $userList -ErrorAction Stop).Count
    if ($machineCount -ne [int]$manifest.MachineFindingCount -or $userCount -ne [int]$manifest.UserFindingCount) {
        throw "Finding list count mismatch. Machine=$machineCount; User=$userCount."
    }

    $script:EngineVerified = $true
    return $manifest
}

function Get-ReportLocations {
    [CmdletBinding()]
    param([string]$RequestedPath)

    if ([string]::IsNullOrWhiteSpace($RequestedPath)) {
        if ($Scope -eq 'Machine') {
            if ([string]::IsNullOrWhiteSpace($env:ProgramData)) {
                throw 'ProgramData is unavailable for the machine report.'
            }
            $basePath = Join-Path $env:ProgramData 'CISWindowsEndpointAssessment\Reports\Machine'
        }
        else {
            if ([string]::IsNullOrWhiteSpace($env:LocalAppData)) {
                throw 'LocalAppData is unavailable for the user report.'
            }
            $basePath = Join-Path $env:LocalAppData 'CISWindowsEndpointAssessment\Reports\User'
        }
        $summaryPath = Join-Path $basePath 'Latest.json'
    }
    else {
        $summaryPath = [System.IO.Path]::GetFullPath($RequestedPath)
        $basePath = Split-Path -Parent $summaryPath
    }

    if (-not (Test-Path -LiteralPath $basePath)) {
        $null = New-Item -Path $basePath -ItemType Directory -Force -ErrorAction Stop
    }
    $rawPath = Join-Path $basePath 'Latest-HardeningKitty.csv'
    [pscustomobject]@{ Summary = $summaryPath; Raw = $rawPath; Directory = $basePath }
}

function Write-Utf8JsonAtomic {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [psobject]$Value,
        [Parameter(Mandatory)] [string]$Path
    )

    $tempPath = Join-Path (Split-Path -Parent $Path) ('.assessment-{0}.json' -f [guid]::NewGuid().ToString('N'))
    try {
        $json = $Value | ConvertTo-Json -Depth 8
        [System.IO.File]::WriteAllText($tempPath, $json, (New-Object System.Text.UTF8Encoding($false)))
        Move-Item -LiteralPath $tempPath -Destination $Path -Force -ErrorAction Stop
    }
    finally {
        Remove-Item -LiteralPath $tempPath -Force -ErrorAction SilentlyContinue
    }
}

function Invoke-HardeningKittyAudit {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$Root,
        [Parameter(Mandatory)] [hashtable]$Manifest,
        [Parameter(Mandatory)] [psobject]$Locations
    )

    $listLeaf = if ($Scope -eq 'Machine') {
        'finding_list_cis_microsoft_windows_11_enterprise_24h2_machine.csv'
    }
    else {
        'finding_list_cis_microsoft_windows_11_enterprise_24h2_user.csv'
    }
    $expectedCount = if ($Scope -eq 'Machine') { [int]$Manifest.MachineFindingCount } else { [int]$Manifest.UserFindingCount }
    $listPath = Join-Path $Root "lists\$listLeaf"
    $modulePath = Join-Path $Root 'HardeningKitty.psd1'
    $temporaryCsv = Join-Path $Locations.Directory ('.hardeningkitty-{0}.csv' -f [guid]::NewGuid().ToString('N'))

    $mutex = New-Object System.Threading.Mutex($false, "Local\CISWindows24H2Assessment-$Scope")
    $lockTaken = $false
    try {
        try {
            $lockTaken = $mutex.WaitOne([TimeSpan]::FromSeconds(10))
        }
        catch [System.Threading.AbandonedMutexException] {
            $lockTaken = $true
        }
        if (-not $lockTaken) {
            throw "Another $Scope assessment is already running."
        }

        Import-Module -Name $modulePath -Force -ErrorAction Stop
        Invoke-HardeningKitty -Mode Audit -Source GPO -FileFindingList $listPath `
            -SkipMachineInformation -SkipUserInformation -SkipLanguageWarning `
            -Report -ReportFile $temporaryCsv -ErrorAction Stop *> $null

        if (-not (Test-Path -LiteralPath $temporaryCsv -PathType Leaf)) {
            throw 'HardeningKitty did not create its CSV report.'
        }
        $rows = @(Import-Csv -LiteralPath $temporaryCsv -ErrorAction Stop)
        if ($rows.Count -ne $expectedCount) {
            throw "HardeningKitty evaluated $($rows.Count) of $expectedCount expected $Scope findings."
        }
        $invalidResults = @($rows | Where-Object TestResult -notin @('Passed', 'Failed'))
        if ($invalidResults.Count -gt 0) {
            throw "HardeningKitty returned $($invalidResults.Count) findings without a valid Passed/Failed result."
        }

        Move-Item -LiteralPath $temporaryCsv -Destination $Locations.Raw -Force -ErrorAction Stop
        return $rows
    }
    finally {
        Remove-Item -LiteralPath $temporaryCsv -Force -ErrorAction SilentlyContinue
        Remove-Module -Name HardeningKitty -Force -ErrorAction SilentlyContinue
        if ($lockTaken) {
            try { $mutex.ReleaseMutex() } catch { }
        }
        $mutex.Dispose()
    }
}

function New-Assessment {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [object[]]$Rows,
        [Parameter(Mandatory)] [psobject]$Locations
    )

    $failures = @($Rows | Where-Object TestResult -eq 'Failed')
    $map = Get-CategorySettingMap
    $categories = [ordered]@{}
    foreach ($category in @($Rows.Category | Sort-Object -Unique)) {
        if (-not $map.Contains($category)) {
            throw "No Custom Compliance mapping exists for HardeningKitty category '$category'."
        }
        $categoryFailures = @($failures | Where-Object Category -eq $category)
        $categories[$map[$category]] = ($categoryFailures.Count -eq 0)
    }

    $results = @(
        foreach ($row in $Rows) {
            [pscustomobject][ordered]@{
                ID              = [string]$row.ID
                Category        = [string]$row.Category
                Name            = [string]$row.Name
                Profile         = [string]$row.Filter
                Status          = [string]$row.TestResult
                Severity        = [string]$row.Severity
                FindingSeverity = [string]$row.SeverityFinding
                Actual          = ConvertTo-SafeText $row.Result
                Recommended     = ConvertTo-SafeText $row.Recommended
                UsedDefault     = [System.Convert]::ToBoolean($row.DefaultValue)
            }
        }
    )

    [pscustomobject][ordered]@{
        AssessmentVersion = $script:AssessmentVersion
        Engine             = 'HardeningKitty'
        EngineVersion      = $script:EngineVersion
        EngineCommit       = $script:EngineCommit
        EngineIntegrity    = $script:EngineVerified
        Benchmark          = $script:BenchmarkName
        BenchmarkVersion   = $script:BenchmarkVersion
        TargetRelease      = $script:TargetRelease
        Coverage           = 'Complete vendored HardeningKitty finding list for selected scope'
        Scope              = $Scope
        StartedUtc         = $script:StartedUtc.ToString('o')
        CompletedUtc       = [DateTime]::UtcNow.ToString('o')
        AssessmentHealthy  = $true
        OverallCompliant   = ($failures.Count -eq 0)
        Evaluated          = $Rows.Count
        Passed             = @($Rows | Where-Object TestResult -eq 'Passed').Count
        Failed             = $failures.Count
        High               = @($failures | Where-Object Severity -eq 'High').Count
        Medium             = @($failures | Where-Object Severity -eq 'Medium').Count
        Low                = @($failures | Where-Object Severity -eq 'Low').Count
        Categories         = [pscustomobject]$categories
        RawReport          = $Locations.Raw
        Results            = $results
    }
}

function Write-CustomComplianceFailure {
    $failure = [ordered]@{
        OverallCompliant  = $false
        AssessmentHealthy = $false
        EngineIntegrity   = [bool]$script:EngineVerified
    }
    foreach ($name in Get-ScopeCategoryNames) {
        $failure[$name] = $false
    }
    Write-Output ([pscustomobject]$failure | ConvertTo-Json -Compress)
}

try {
    Test-TargetPlatform
    if ([string]::IsNullOrWhiteSpace($EngineRoot)) {
        $EngineRoot = Get-DefaultEngineRoot
    }
    $EngineRoot = [System.IO.Path]::GetFullPath($EngineRoot)
    $manifest = Test-EnginePackage -Root $EngineRoot
    $locations = Get-ReportLocations -RequestedPath $ReportPath
    $rows = @(Invoke-HardeningKittyAudit -Root $EngineRoot -Manifest $manifest -Locations $locations)
    $assessment = New-Assessment -Rows $rows -Locations $locations
    Write-Utf8JsonAtomic -Value $assessment -Path $locations.Summary

    switch ($OutputMode) {
        'CustomCompliance' {
            $discovery = [ordered]@{
                OverallCompliant  = [bool]$assessment.OverallCompliant
                AssessmentHealthy = $true
                EngineIntegrity   = $true
            }
            foreach ($property in $assessment.Categories.PSObject.Properties) {
                $discovery[$property.Name] = [bool]$property.Value
            }
            Write-Output ([pscustomobject]$discovery | ConvertTo-Json -Compress)
            exit 0
        }
        'IntuneRemediation' {
            if ($assessment.OverallCompliant) {
                Write-Output "CIS 24H2 $Scope audit passed: $($assessment.Passed)/$($assessment.Evaluated) findings. Detail: $($locations.Summary)"
                exit 0
            }
            $problemIds = @($assessment.Results | Where-Object Status -eq 'Failed' | Select-Object -ExpandProperty ID -First 20) -join ','
            Write-Output "CIS 24H2 $Scope audit noncompliant: $($assessment.Failed) fail ($($assessment.High) high/$($assessment.Medium) medium/$($assessment.Low) low). IDs: $problemIds. Detail: $($locations.Summary)"
            exit 1
        }
        'Detailed' {
            if ($PassThru) { Write-Output $assessment } else { Write-Output ($assessment | ConvertTo-Json -Depth 8) }
            if ($assessment.OverallCompliant) { exit 0 } else { exit 1 }
        }
    }
}
catch {
    $message = ConvertTo-SafeText -Value $_.Exception.Message -MaximumLength 900
    if ($OutputMode -eq 'CustomCompliance') {
        Write-CustomComplianceFailure
    }
    elseif ($OutputMode -eq 'IntuneRemediation') {
        Write-Output "CIS 24H2 $Scope assessment failed to run; review endpoint diagnostics."
    }
    else {
        Write-Output "CIS 24H2 $Scope assessment failed to run: $message"
    }
    exit 1
}
