#requires -Version 5.1

[CmdletBinding()]
param()

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

$sourcePath = Join-Path $PSScriptRoot 'Invoke-CISWindows24H2Assessment.ps1'
$deployPath = Join-Path $PSScriptRoot 'Deploy'
$modeDeclaration = "[string]`$OutputMode = 'Detailed'"
$scopeDeclaration = "[string]`$Scope = 'Machine'"
$targets = @(
    [pscustomobject]@{ RelativePath = 'Machine\Detect-CISWindows24H2MachineCompliance.ps1'; Scope = 'Machine'; Mode = 'IntuneRemediation' }
    [pscustomobject]@{ RelativePath = 'Machine\Discover-CISWindows24H2MachineCompliance.ps1'; Scope = 'Machine'; Mode = 'CustomCompliance' }
    [pscustomobject]@{ RelativePath = 'User\Detect-CISWindows24H2UserCompliance.ps1'; Scope = 'User'; Mode = 'IntuneRemediation' }
    [pscustomobject]@{ RelativePath = 'User\Discover-CISWindows24H2UserCompliance.ps1'; Scope = 'User'; Mode = 'CustomCompliance' }
)

& (Join-Path $PSScriptRoot 'Build-CustomComplianceRules.ps1') | Out-Null
$source = [System.IO.File]::ReadAllText($sourcePath)
foreach ($declaration in @($modeDeclaration, $scopeDeclaration)) {
    $occurrences = ([regex]::Matches($source, [regex]::Escape($declaration))).Count
    if ($occurrences -ne 1) {
        throw "Expected one '$declaration' declaration in $sourcePath; found $occurrences."
    }
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
foreach ($target in $targets) {
    $content = $source.Replace($modeDeclaration, ("[string]`$OutputMode = '{0}'" -f $target.Mode))
    $content = $content.Replace($scopeDeclaration, ("[string]`$Scope = '{0}'" -f $target.Scope))
    if ($target.Mode -eq 'IntuneRemediation') {
        $content = $content.Replace('Detail: $($locations.Summary)', 'Detail report updated locally.')
    }
    $content = "# Generated by Build-IntunePackage.ps1 for $($target.Scope)/$($target.Mode). Edit the source, not this file.`n" + $content
    $targetPath = Join-Path $deployPath $target.RelativePath
    $targetDirectory = Split-Path -Parent $targetPath
    if (-not (Test-Path -LiteralPath $targetDirectory)) {
        $null = New-Item -Path $targetDirectory -ItemType Directory -Force
    }
    [System.IO.File]::WriteAllText($targetPath, $content, $utf8NoBom)
    Write-Output "Built $targetPath"
}
